---
#

- name: Configure splunk cluster master
  shell: /opt/splunk/bin/splunk edit cluster-config -mode {{ cluster_mode }} -multisite {{ multisite_status }} -replication_factor 2 -available_sites {{ available_sites }} -site site{{ master_residence_site }} -site_replication_factor {{ site_replication_factor }} -site_search_factor {{ site_search_factor }} -secret {{ idxcluster_secret }} -auth {{ splkuser }}:{{ splkpass }}
  become: yes
  become_user: splunk
  ignore_errors: yes

- name: Restart Splunk
  shell: /opt/splunk/bin/splunk restart
  become: yes
  become_user: splunk
