---
# This playbook contains the tasks to reset instance and remove all traces of former setup.

- name: Delete Splunk User
  command: sudo userdel -f splunk 
  ignore_errors: yes

- name: Delete Splunk User Directory
  command: sudo rm -rf /home/splunk
  ignore_errors: yes
  

- name: Delete Splunk Installation Binary
  command: sudo rm -rf /opt/{{splunk_enterprise}}
  ignore_errors: yes  

- name: Delete Splunk Files 
  command: sudo rm -rf /opt/splunk
  ignore_errors: yes

- name: Delete Splunk Forwader Installation Binary
  command: sudo rm -rf /opt/{{splunk_forwarder}}
  ignore_errors: yes  

- name: Delete Splunk Forwarder Files 
  command: sudo rm -rf /opt/splunkforwarder
  ignore_errors: yes

- name: Delete Splunk Base Config Files 
  command: sudo rm -rf /var/tmp/base_configs
  ignore_errors: yes

- name: Kill running splunkd processes
  shell: pkill splunkd
  ignore_errors: yes

- name: Kill running mongo db processes
  shell: pkill mongod
  ignore_errors: yes

- name: Delete Ansible Retry Files
  command: sudo rm -rf ~/teku-splunk-ansible/*.retry
  ignore_errors: yes
