- name: Copy base configs
  copy: src={{ deploypackages }}{{ base_configs }} dest=/var/tmp owner=splunk group=splunk mode=0755

- name: Edit outputs base config master value
  replace:
    path: "/var/tmp/base_configs/org_all_core_outputs/local/outputs.conf"
    regexp: '<master>'
    replace: "{{ master_internal_ip }}"
    backup: yes

- name: Edit outputs base config secret value
  replace:
    path: "/var/tmp/base_configs/org_all_core_outputs/local/outputs.conf"
    regexp: '<secret>'
    replace: "{{ discoverysecret }}"
    backup: yes

- name: Edit deployer base config secret value
  replace:
    path: "/var/tmp/base_configs/org_all_deployer_base/local/server.conf"
    regexp: '<shcluster_secret>'
    replace: "{{ shcluster_secret }}"
    backup: yes

- name: Edit deployer base config label
  replace:
    path: "/var/tmp/base_configs/org_all_deployer_base/local/server.conf"
    regexp: '<shcluster_label>'
    replace: "{{ shcluster_label }}"
    backup: yes

- name: Copy base configs to app path
  shell: cp -a "/var/tmp/base_configs/org_all_core_outputs" /opt/splunk/etc/apps/

- name: Copy base configs to app path
  shell: cp -a "/var/tmp/base_configs/org_all_deployer_base" /opt/splunk/etc/apps/

- name: Fix 'app' permissions
  file: path=/opt/splunk/etc/apps owner=splunk group=splunk mode=0755 state=directory recurse=yes
