- name: Copy base configs
  copy: src={{ deploypackages }}{{ base_configs }} dest=/var/tmp owner=splunk group=splunk mode=0755

- name: Edit outputs base config master value
  replace:
    path: "/var/tmp/base_configs/org_all_core_outputs/local/outputs.conf"
    regexp: '<master>'
    replace: "{{ master_internal_ip }}"
    backup: yes

- name: Edit outputs base config secret value
  replace:
    path: "/var/tmp/base_configs/org_all_core_outputs/local/outputs.conf"
    regexp: '<secret>'
    replace: "{{ discoverysecret }}"
    backup: yes

- name: Copy base configs to app path
  shell: cp -a "/var/tmp/base_configs/org_all_core_outputs" /opt/splunk/etc/apps/

- name: Copy base configs to app path
  shell: cp -a "/var/tmp/base_configs/org_all_deployer_base" /opt/splunk/etc/apps/

- name: Configure Splunk as Deployer
  copy: src=server.conf dest=/opt/splunk/etc/system/local/ owner=splunk group=splunk mode=0755

- name: Edit server cluster config for search head secret pass4symm value
  replace:
    path: "/opt/splunk/etc/system/local/server.conf"
    regexp: '<shcluster_secret>'
    replace: "{{ shcluster_secret }}"
    backup: yes

- name: Edit server cluster config for search head cluster label
  replace:
    path: "/opt/splunk/etc/system/local/server.conf"
    regexp: '<shcluster_lable>'
    replace: "{{ shcluster_label }}"
    backup: yes

- name: Fix 'app' permissions
  file: path=/opt/splunk/etc/apps owner=splunk group=splunk mode=0755 state=directory recurse=yes

- name: Restart Splunk
  shell: /opt/splunk/bin/splunk restart
  become: yes
  become_user: splunk
