---
# This playbook will install Splunk Enterprise and configure as an indexer slave.

- name: Copy installer
  copy: src={{ deploypackages }}{{ enterprise }} dest=/var/tmp/ owner=ec2-user group=ec2-user mode=0644

- name: Install Splunk Enterprise package
  yum:
    name: /var/tmp/{{ enterprise }}
    state: installed

- name: Configure boot-start with splunk user
  shell: /opt/splunk/bin/splunk enable boot-start -user splunk --accept-license

- name: Copy base configs
  unarchive: src={{ deploypackages }}{{ base_configs }} dest=/opt/ owner=splunk group=splunk mode=0744

- name: Copy base configs to app path
  shell: cp -a "/opt/Configurations-Base/{{ org }}_all_indexer_base" /opt/splunk/etc/apps/

- name: Start Splunk
  shell: /opt/splunk/bin/splunk start
  become: yes
  become_user: splunk

- name: Configure splunk cluster slave
  shell: /opt/splunk/bin/splunk edit cluster-config -master_uri https://{{ master_internal_ip }}:8089 -mode slave -multisite true -site site1 -replication_port 9887 -secret {{ clustersecret }} -auth admin:changeme
  become: yes
  become_user: splunk

- name: Fix 'app' permissions
  file: path=/opt/splunk/etc/apps owner=splunk group=splunk mode=0755 state=directory recurse=yes

- name: cleanup files
  shell: find /opt/splunk/etc/apps -type f -name '._*' -delete && find /opt/splunk/etc/apps -type f -name '*.conf.*' -delete && find /opt/splunk/etc/apps -type f -name '.DS_Store' -delete

- name: Restart Splunk
  shell: /opt/splunk/bin/splunk restart
  become: yes
  become_user: splunk
