- name: Configure OS and install Splunk
  vars: 
    description: 'Common Configuration and settings for all Splunk Enterprise Deployments - except for Splunk Forwarder.'
  hosts: all
  remote_user: centos
  become: yes

  roles:
    - common
