- name: Configure Splunk Instances as License Slaves
  vars: 
    description: 'Configure Splunk Instances as License Slaves'
  hosts: license_slaves
  remote_user: centos
  become: yes

  roles:
    - license_pool
