- name: Configure Splunk Instances as License Slaves
  vars: 
    description: 'Configure Splunk Instances as License Slaves and then restart them.'
  hosts: all
  remote_user: centos
  become: yes

  roles:
    - license_pool
