---
# This playbook will install Splunk Enterprise and configure as a utility server.

- name: Copy installer
  copy: src={{ deploypackages }}{{ enterprise }} dest=/var/tmp/ owner=ec2-user group=ec2-user mode=0644

- name: Install Splunk Enterprise package
  yum:
    name: /var/tmp/{{ enterprise }}
    state: installed

- name: Configure boot-start with splunk user
  shell: /opt/splunk/bin/splunk enable boot-start -user splunk --accept-license

- name: Copy base configs
  unarchive: src={{ deploypackages }}{{ base_configs }} dest=/opt/ owner=splunk group=splunk mode=0744

- name: Edit outputs base config master value
  replace:
    path: "/opt/Configurations-Base/{{ org }}_all_core_outputs/local/outputs.conf"
    regexp: '<master>'
    replace: "{{ master_internal_ip }}"
    backup: yes

- name: Edit outputs base config secret value
  replace:
    path: "/opt/Configurations-Base/{{ org }}_all_core_outputs/local/outputs.conf"
    regexp: '<secret>'
    replace: "{{ discoverysecret }}"
    backup: yes

- name: Copy base configs to app path
  shell: cp -a "/opt/Configurations-Base/{{ org }}_all_core_outputs" /opt/splunk/etc/apps/

- name: Start Splunk
  shell: /opt/splunk/bin/splunk start
  become: yes
  become_user: splunk
