---
# This playbook will install Splunk Enterprise and configure as a search head cluster member.

- name: Copy installer
  copy: src={{ deploypackages }}{{ enterprise }} dest=/var/tmp/ owner=ec2-user group=ec2-user mode=0644

- name: Install Splunk Enterprise package
  yum:
    name: /var/tmp/{{ enterprise }}
    state: installed

- name: Configure boot-start with splunk user
  shell: /opt/splunk/bin/splunk enable boot-start -user splunk --accept-license

- name: Copy base configs
  unarchive: src={{ deploypackages }}{{ base_configs }} dest=/opt/ owner=splunk group=splunk mode=0744

- name: Edit outputs base config master value
  replace:
    path: "/opt/Configurations-Base/{{ org }}_all_core_outputs/local/outputs.conf"
    regexp: '<master>'
    replace: "{{ master_internal_ip }}"
    backup: yes

- name: Edit outputs base config secret value
  replace:
    path: "/opt/Configurations-Base/{{ org }}_all_core_outputs/local/outputs.conf"
    regexp: '<secret>'
    replace: "{{ discoverysecret }}"
    backup: yes

- name: Copy base configs to app path
  shell: cp -a "/opt/Configurations-Base/{{ org }}_all_core_outputs" /opt/splunk/etc/apps/

- name: Copy base configs to app path
  shell: cp -a "/opt/Configurations-Base/{{ org }}_all_search_base" /opt/splunk/etc/apps/

- name: Start Splunk
  shell: /opt/splunk/bin/splunk start
  become: yes
  become_user: splunk

- name: Configure splunk to join index cluster
  shell: /opt/splunk/bin/splunk edit cluster-config -master_uri https://{{ master_internal_ip }}:8089 -mode searchhead -multisite true -site site1 -replication_port 9887 -secret {{ clustersecret }} -auth admin:changeme
  become: yes
  become_user: splunk

- name: Configure splunk as search cluster member
  shell: /opt/splunk/bin/splunk init shcluster-config -auth admin:changeme -mgmt_uri https://{{ ansible_eth0.ipv4.address }}:8089 -replication_port 9980 -replication_factor 2 -conf_deploy_fetch_url https://{{ deployer_internal_ip }}:8089 -secret {{ clustersecret }} -shcluster_label {{ clusterlabel }}
  become: yes
  become_user: splunk

- name: Fix 'app' permissions
  file: path=/opt/splunk/etc/apps owner=splunk group=splunk mode=0755 state=directory recurse=yes

- name: cleanup files
  shell: find /opt/splunk/etc/apps -type f -name '._*' -delete && find /opt/splunk/etc/apps -type f -name '*.conf.*' -delete && find /opt/splunk/etc/apps -type f -name '.DS_Store' -delete

- name: Restart Splunk
  shell: /opt/splunk/bin/splunk restart
  become: yes
  become_user: splunk
