- name: Install all common configs
  hosts: all
  remote_user: ec2-user
  become: yes

  roles:
    - common

- name: Install and configure the index cluster master
  hosts: master
  remote_user: ec2-user
  become: yes

  roles:
#    - common
    - master

- name: Install and configure the deployer
  hosts: deployer
  remote_user: ec2-user
  become: yes

  roles:
#    - common
    - deployer

- name: Install and configure the site1-indexer
  hosts: site1-indexer
  remote_user: ec2-user
  become: yes

  roles:
#    - common
    - site1-indexer

- name: Install and configure the site2-indexer
  hosts: site2-indexer
  remote_user: ec2-user
  become: yes

  roles:
#    - common
    - site2-indexer

- name: Install and configure the site1-search
  hosts: site1-search
  remote_user: ec2-user
  become: yes

  roles:
#    - common
    - site1-search

- name: Install and configure the site2-search
  hosts: site2-search
  remote_user: ec2-user
  become: yes

  roles:
#    - common
    - site2-search

- name: Install and configure the monitoring console
  hosts: monitor
  remote_user: ec2-user
  become: yes

  roles:
#    - common
    - monitor

- name: Install and configure the deployment server
  hosts: deployment
  remote_user: ec2-user
  become: yes

  roles:
#    - common
    - deployment
