---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp

- name: Install common dependencies
  yum: name={{ item }} state=installed
  with_items:
   - libselinux-python
   - libsemanage-python

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp

- name: Set open files limit for splunk
  copy: src=90-nofile.conf dest=/etc/security/limits.d/ owner=root group=root mode=0644

- name: Set max processes limit
  copy: src=90-nproc.conf dest=/etc/security/limits.d/ owner=root group=root mode=0644

- name: Copy Disable THP File
  copy: src=disable-thp dest=/etc/init.d/ owner=root group=root mode=0755

- name: Disable THP
  shell: chkconfig --add disable-thp

- sysctl:
    name: net.ipv4.tcp_rmem
    value: 4096 87380 33554432
    sysctl_file: /etc/sysctl.d/ipv4.conf
    reload: yes

- sysctl:
    name: net.ipv4.tcp_wmem
    value: 4096 65536 33554432
    sysctl_file: /etc/sysctl.d/ipv4.conf
    reload: yes

- sysctl:
    name: net.ipv4.tcp_no_metrics_save
    value: 1
    sysctl_file: /etc/sysctl.d/ipv4.conf
    reload: yes

- sysctl:
    name: net.core.rmem_max
    value: 33554432
    sysctl_file: /etc/sysctl.d/netCore.conf
    reload: yes

- sysctl:
    name: net.core.wmem_max
    value: 33554432
    sysctl_file: /etc/sysctl.d/netCore.conf
    reload: yes
