---
# This playbook will configure Splunk  as a search head cluster member.


- name: Configure splunk to join cluster master node as search head
  shell: /opt/splunk/bin/splunk edit cluster-config -master_uri https://{{ master_internal_ip }}:8089 -mode {{ membermode }} -secret {{ idxcluster_secret }} -auth admin:changeme
  become: yes
  become_user: splunk

- name: Configure splunk as search cluster member if standalone is False
  shell: /opt/splunk/bin/splunk init shcluster-config -auth admin:changeme -mgmt_uri https://"$(hostname -f)":8089 -replication_port {{ shc_rep_port }} -replication_factor 2 -conf_deploy_fetch_url https://{{ deployer_internal_ip }}:8089 -secret {{ shcluster_secret }} -shcluster_label {{ shcluster_label }}
  become: yes
  become_user: splunk

- name: Restart Splunk
  shell: /opt/splunk/bin/splunk restart
  become: yes
  become_user: splunk
