---
# This playbook contains cleanup items for Splunk platform

- name: Fix 'app' permissions
  file: path=/opt/splunk/etc/apps owner=splunk group=splunk mode=0755 state=directory recurse=yes

- name: cleanup files
  shell: find /opt/splunk/etc/apps/splk* -type f -name '._*' -delete && find /opt/splunk/etc/apps/splk* -type f -name '*.conf.*' -delete && find /opt/splunk/etc/apps/splk* -type f -name '.DS_Store' -delete

- name: Restart Splunk
  shell: /opt/splunk/bin/splunk restart
  become: yes
  become_user: splunk
