---
# This playbook contains common plays that will be run on all nodes.
#
- name: Set open files limit for splunk
  copy: src=20-nofile.conf dest=/etc/security/limits.d/ owner=root group=root mode=0755

- name: Set max processes limit
  copy: src=20-nproc.conf dest=/etc/security/limits.d/ owner=root group=root mode=0755

- name: Set core file size
  copy: src=20-core.conf dest=/etc/security/limits.d/ owner=root group=root mode=0755

- name: Copy Disable THP File
  copy: src=disable-thp dest=/etc/init.d/ owner=root group=root mode=0755

- name: Disable Transparent Huge Page
  shell: chkconfig --add disable-thp

- name: Download Splunk
  get_url: url={{wget_url_splunk_enterprise}} dest=/opt/ owner=root group=root mode=0755

- name: Install Splunk Enterprise package
  command: tar -xvzf /opt/{{splunk_enterprise}} -C /opt 

- name: Add Splunk User   
  command: sudo useradd -m -r splunk 

- name: Assign Password to Splunk User
  command: echo 'password' | sudo passwd splunk --stdin 

- name: Assign /opt/splunk to Splunk Service User
  command: sudo chown -R splunk:splunk /opt/splunk 

- name: Configure boot-start with splunk user
  shell: /opt/splunk/bin/splunk enable boot-start -user splunk --accept-license --answer-yes

- name: Start Splunk
  shell: /opt/splunk/bin/splunk restart
  become: yes
  become_user: splunk

