---
# This playbook contains common plays that will be run on all nodes.
#
- name: Set open files limit for splunk
  copy: src=20-nofile.conf dest=/etc/security/limits.d/ owner=root group=root mode=0755

- name: Set max processes limit
  copy: src=20-nproc.conf dest=/etc/security/limits.d/ owner=root group=root mode=0755

- name: Set core file size
  copy: src=20-core.conf dest=/etc/security/limits.d/ owner=root group=root mode=0755

- name: Copy Disable THP File
  copy: src=disable-thp dest=/etc/init.d/ owner=root group=root mode=0755

- name: Disable Transparent Huge Page
  shell: sudo chkconfig --add disable-thp

- name: Download Splunk
  get_url: url={{wget_url_splunk_enterprise}} dest=/opt/ owner=root group=root mode=0755

- name: Install Splunk Enterprise package
  unarchive: 
   src: /opt/{{splunk_enterprise}} 
   dest: /opt/ 

- name: Add Splunk Service User   
  command: sudo useradd -m -r splunk 
  ignore_errors: yes  

- name: Assign Password to Splunk Service User
  command: echo 'password' | sudo passwd splunk --stdin 

- name: Assign /opt/splunk to Splunk Service User
  command: sudo chown -R splunk:splunk /opt/splunk 

- name: Copy User-Seed  
  copy: src=user-seed.conf dest=/opt/splunk/etc/system/local/ owner=splunk group=splunk mode=0755

- name: Configure boot-start with Splunk user
  shell: /opt/splunk/bin/splunk enable boot-start -user splunk --accept-license --answer-yes --no-prompt
  ignore_errors: yes 

#- name: Copy Deployment Client Configs from 
#  copy: src=deploymentclient.conf dest=/opt/splunk/etc/system/local/ owner=splunk group=splunk mode=0755

- name: Start Splunk
  shell: /opt/splunk/bin/splunk start --answer-yes
  become: yes
  become_user: splunk
