---
# This playbook will configure Splunk as a cluster master.
# It relies of having all base configs built already, for information on this,
# please contact Teku Professional Services @ www.tekugroup.net


- name: Copy base configs
  copy: src={{ deploypackages }}{{ base_configs }} dest=/var/tmp owner=splunk group=splunk mode=0755

- name: Edit outputs base config master value
  replace:
    path: "/var/tmp/base_configs/org_all_core_outputs/local/outputs.conf"
    regexp: '<master>'
    replace: "{{ master_internal_ip }}"
    backup: yes

- name: Edit outputs base config indexer discoevry secret value
  replace:
    path: "/var/tmp/base_configs/org_all_core_outputs/local/outputs.conf"
    regexp: '<discoverysecret>'
    replace: "{{ discoverysecret }}"
    backup: yes

- name: Edit server base config - indexer discoery secret value
  replace:
    path: "/var/tmp/base_configs/org_cm_base/local/server.conf"
    regexp: '<discoverysecret>'
    replace: "{{ discoverysecret }}"
    backup: yes

- name: Edit server base config clustering secret pass4symm value
  replace:
    path: "/var/tmp/base_configs/org_cm_base/local/server.conf"
    regexp: '<idxcluster_secret>'
    replace: "{{ idxcluster_secret }}"
    backup: yes

- name: Copy global outputs config to app path
  shell: cp -a "/var/tmp/base_configs/org_all_core_outputs" /opt/splunk/etc/apps/

- name: Copy cm role configs to app path
  shell: cp -a "/var/tmp/base_configs/org_cm_base" /opt/splunk/etc/apps/

- name: Fix 'app' permissions
  file: path=/opt/splunk/etc/apps owner=splunk group=splunk mode=0755 state=directory recurse=yes

- name: Restart Splunk
  shell: /opt/splunk/bin/splunk restart
  become: yes
  become_user: splunk
