---
# This playbook will install Splunk Enterprise and configure as a cluster master.

- name: Copy installer
  copy: src={{ deploypackages }}{{ enterprise }} dest=/var/tmp/ owner=ec2-user group=ec2-user mode=0644

- name: Install Splunk Enterprise package
  yum:
    name: /var/tmp/{{ enterprise }}
    state: installed

- name: Configure boot-start with splunk user
  shell: /opt/splunk/bin/splunk enable boot-start -user splunk --accept-license

- name: Copy base configs
  unarchive: src={{ deploypackages }}{{base_configs}} dest=/opt/ owner=splunk group=splunk mode=0744

- name: Edit outputs base config master value
  replace:
    path: "/opt/Configurations-Base/{{ org }}_all_core_outputs/local/outputs.conf"
    regexp: '<master>'
    replace: "{{ master_internal_ip }}"
    backup: yes

- name: Edit outputs base config secret value
  replace:
    path: "/opt/Configurations-Base/{{ org }}_all_core_outputs/local/outputs.conf"
    regexp: '<secret>'
    replace: "{{ discoverysecret }}"
    backup: yes

- name: Edit server base config secret value
  replace:
    path: "/opt/Configurations-Base/{{ org }}_cluster_master_base/local/server.conf"
    regexp: '<secret>'
    replace: "{{ discoverysecret }}"
    backup: yes

- name: Edit server base config clustering secred value
  replace:
    path: "/opt/Configurations-Base/{{ org }}_cluster_master_base/local/server.conf"
    regexp: '<clustersecret>'
    replace: "{{ clustersecret }}"
    backup: yes

- name: Copy role configs to app path
  shell: cp -a "/opt/Configurations-Base/{{ org }}_cluster_master_base" /opt/splunk/etc/apps/

- name: Copy base configs to app path
  shell: cp -a "/opt/Configurations-Base/{{ org }}_all_core_outputs" /opt/splunk/etc/apps/

- name: Start Splunk
  shell: /opt/splunk/bin/splunk start
  become: yes
  become_user: splunk

- name: Configure splunk cluster master
  shell: /opt/splunk/bin/splunk edit cluster-config -mode master -multisite true -replication_factor 2 -available_sites site1,site2 -site site1 -site_replication_factor origin:1,total:2 -site_search_factor origin:1,total:2  -auth admin:changeme
  become: yes
  become_user: splunk

- name: Fix 'app' permissions
  file: path=/opt/splunk/etc/apps owner=splunk group=splunk mode=0755 state=directory recurse=yes

- name: cleanup files
  shell: find /opt/splunk/etc/apps -type f -name '._*' -delete && find /opt/splunk/etc/apps -type f -name '*.conf.*' -delete && find /opt/splunk/etc/apps -type f -name '.DS_Store' -delete

- name: Restart Splunk
  shell: /opt/splunk/bin/splunk restart
  become: yes
  become_user: splunk
