---
# This role contains plays to configure the License Master

- name: Create license folder
  command: mkdir /opt/splunk/licenses 
  ignore_errors: yes



- name: Install license key
 # shell: /opt/splunk/bin/splunk add licenses splunk.lic"
 # become: yes
 # become_user: splunk
 # ignore_errors: yes

#- name: Restart Splunk
#  command: /opt/splunk/bin/splunk restart --answer-yes

